foreground              #e9f1f4
background              #3e4b52
selection_foreground    #252f34
selection_background    #ece0b0

cursor                  #d6e6ec
cursor_text_color       #252f34

url_color               #e3dccf

active_border_color     #d6e6ec
inactive_border_color   #4a5960
bell_border_color       #ff6b6b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #252f34
active_tab_background   #cfe1e8
inactive_tab_foreground #93a7b1
inactive_tab_background #3e4b52
tab_bar_background      #252f34

mark1_foreground #252f34
mark1_background #d6e6ec
mark2_foreground #252f34
mark2_background #cfe4d8
mark3_foreground #252f34
mark3_background #e3dccf

color0 #4a5960
color8 #b7c7cf

color1 #ff6b6b
color9 #c9d9df

color2  #d6e6ec
color10 #cfe1e8

color3  #e3dccf
color11 #d6e6ec

color4  #cfe4d8
color12 #ece0b0

color5  #cfe1e8
color13 #d6e6ec

color6  #ece0b0
color14 #d6e6ec

color7  #93a7b1
color15 #e9f1f4
