background #0b0f12
foreground #dee3e8
selection_background #8fcef3
selection_foreground #00344a
cursor #8fcef3
cursor_text_color #00344a
url_color #c6c2ea
active_border_color #8fcef3
inactive_border_color #41484d
active_tab_background #8fcef3
active_tab_foreground #00344a
inactive_tab_background #1b2024
inactive_tab_foreground #c0c7ce

color0 #252b2f
color8 #8a9198
color1 #ffb4ab
color9 #ffb4ab
color2 #b5c9d7
color10 #b5c9d7
color3 #c6c2ea
color11 #c6c2ea
color4 #8fcef3
color12 #8fcef3
color5 #454364
color13 #c6c2ea
color6 #004c69
color14 #8fcef3
color7 #c0c7ce
color15 #dee3e8
