hl.on("hyprland.start", function()
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("easyeffects -w")
  hl.exec_cmd("zone-cd start")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("blueman-applet")
end)
