$background = rgb({{colors.surface_container_lowest.default.hex_stripped}})
$surface = rgba({{colors.surface_container.default.hex_stripped}}cc)
$foreground = rgb({{colors.on_surface.default.hex_stripped}})
$subtle = rgb({{colors.on_surface_variant.default.hex_stripped}})
$accent = rgb({{colors.primary.default.hex_stripped}})
$error = rgb({{colors.error.default.hex_stripped}})
